//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("LibraryModel", "fk_Book_publisher", "Publisher", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Agrond.Lycute.DAO.Publisher), "Book", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Agrond.Lycute.DAO.Book), true)]
[assembly: EdmRelationshipAttribute("LibraryModel", "Author_Book", "Author", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Agrond.Lycute.DAO.Author), "Book", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Agrond.Lycute.DAO.Book))]
[assembly: EdmRelationshipAttribute("LibraryModel", "fk_Category_Book_ctgID", "Category", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Agrond.Lycute.DAO.Category), "Book", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Agrond.Lycute.DAO.Book), true)]
[assembly: EdmRelationshipAttribute("LibraryModel", "Tag_Book", "Book", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Agrond.Lycute.DAO.Book), "Tag", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Agrond.Lycute.DAO.Tag))]
[assembly: EdmRelationshipAttribute("LibraryModel", "fk_Book_Language_lngID", "Language", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Agrond.Lycute.DAO.Language), "Book", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Agrond.Lycute.DAO.Book), true)]
[assembly: EdmRelationshipAttribute("LibraryModel", "fk_Book_Seri_seriID", "Seri", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Agrond.Lycute.DAO.Seri), "Book", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Agrond.Lycute.DAO.Book), true)]

#endregion

namespace Agrond.Lycute.DAO
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class LibraryEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new LibraryEntities object using the connection string found in the 'LibraryEntities' section of the application configuration file.
        /// </summary>
        public LibraryEntities() : base("name=LibraryEntities", "LibraryEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new LibraryEntities object.
        /// </summary>
        public LibraryEntities(string connectionString) : base(connectionString, "LibraryEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new LibraryEntities object.
        /// </summary>
        public LibraryEntities(EntityConnection connection) : base(connection, "LibraryEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Author> Authors
        {
            get
            {
                if ((_Authors == null))
                {
                    _Authors = base.CreateObjectSet<Author>("Authors");
                }
                return _Authors;
            }
        }
        private ObjectSet<Author> _Authors;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Book> Books
        {
            get
            {
                if ((_Books == null))
                {
                    _Books = base.CreateObjectSet<Book>("Books");
                }
                return _Books;
            }
        }
        private ObjectSet<Book> _Books;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Publisher> Publishers
        {
            get
            {
                if ((_Publishers == null))
                {
                    _Publishers = base.CreateObjectSet<Publisher>("Publishers");
                }
                return _Publishers;
            }
        }
        private ObjectSet<Publisher> _Publishers;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Category> Categories
        {
            get
            {
                if ((_Categories == null))
                {
                    _Categories = base.CreateObjectSet<Category>("Categories");
                }
                return _Categories;
            }
        }
        private ObjectSet<Category> _Categories;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Tag> Tags
        {
            get
            {
                if ((_Tags == null))
                {
                    _Tags = base.CreateObjectSet<Tag>("Tags");
                }
                return _Tags;
            }
        }
        private ObjectSet<Tag> _Tags;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Language> Languages
        {
            get
            {
                if ((_Languages == null))
                {
                    _Languages = base.CreateObjectSet<Language>("Languages");
                }
                return _Languages;
            }
        }
        private ObjectSet<Language> _Languages;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Seri> Seris
        {
            get
            {
                if ((_Seris == null))
                {
                    _Seris = base.CreateObjectSet<Seri>("Seris");
                }
                return _Seris;
            }
        }
        private ObjectSet<Seri> _Seris;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Authors EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToAuthors(Author author)
        {
            base.AddObject("Authors", author);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Books EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToBooks(Book book)
        {
            base.AddObject("Books", book);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Publishers EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPublishers(Publisher publisher)
        {
            base.AddObject("Publishers", publisher);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Categories EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCategories(Category category)
        {
            base.AddObject("Categories", category);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Tags EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTags(Tag tag)
        {
            base.AddObject("Tags", tag);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Languages EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToLanguages(Language language)
        {
            base.AddObject("Languages", language);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Seris EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSeris(Seri seri)
        {
            base.AddObject("Seris", seri);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LibraryModel", Name="Author")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Author : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Author object.
        /// </summary>
        /// <param name="ath_ID">Initial value of the ath_ID property.</param>
        public static Author CreateAuthor(global::System.Int32 ath_ID)
        {
            Author author = new Author();
            author.ath_ID = ath_ID;
            return author;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ath_ID
        {
            get
            {
                return _ath_ID;
            }
            set
            {
                if (_ath_ID != value)
                {
                    Onath_IDChanging(value);
                    ReportPropertyChanging("ath_ID");
                    _ath_ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ath_ID");
                    Onath_IDChanged();
                }
            }
        }
        private global::System.Int32 _ath_ID;
        partial void Onath_IDChanging(global::System.Int32 value);
        partial void Onath_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ath_Name
        {
            get
            {
                return _ath_Name;
            }
            set
            {
                Onath_NameChanging(value);
                ReportPropertyChanging("ath_Name");
                _ath_Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ath_Name");
                Onath_NameChanged();
            }
        }
        private global::System.String _ath_Name;
        partial void Onath_NameChanging(global::System.String value);
        partial void Onath_NameChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LibraryModel", "Author_Book", "Book")]
        public EntityCollection<Book> Books
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Book>("LibraryModel.Author_Book", "Book");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Book>("LibraryModel.Author_Book", "Book", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LibraryModel", Name="Book")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Book : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Book object.
        /// </summary>
        /// <param name="bok_ID">Initial value of the bok_ID property.</param>
        public static Book CreateBook(global::System.Int32 bok_ID)
        {
            Book book = new Book();
            book.bok_ID = bok_ID;
            return book;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 bok_ID
        {
            get
            {
                return _bok_ID;
            }
            set
            {
                if (_bok_ID != value)
                {
                    Onbok_IDChanging(value);
                    ReportPropertyChanging("bok_ID");
                    _bok_ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("bok_ID");
                    Onbok_IDChanged();
                }
            }
        }
        private global::System.Int32 _bok_ID;
        partial void Onbok_IDChanging(global::System.Int32 value);
        partial void Onbok_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String bok_Title
        {
            get
            {
                return _bok_Title;
            }
            set
            {
                Onbok_TitleChanging(value);
                ReportPropertyChanging("bok_Title");
                _bok_Title = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("bok_Title");
                Onbok_TitleChanged();
            }
        }
        private global::System.String _bok_Title;
        partial void Onbok_TitleChanging(global::System.String value);
        partial void Onbok_TitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> bok_Year
        {
            get
            {
                return _bok_Year;
            }
            set
            {
                Onbok_YearChanging(value);
                ReportPropertyChanging("bok_Year");
                _bok_Year = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("bok_Year");
                Onbok_YearChanged();
            }
        }
        private Nullable<global::System.Int32> _bok_Year;
        partial void Onbok_YearChanging(Nullable<global::System.Int32> value);
        partial void Onbok_YearChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String bok_Rank
        {
            get
            {
                return _bok_Rank;
            }
            set
            {
                Onbok_RankChanging(value);
                ReportPropertyChanging("bok_Rank");
                _bok_Rank = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("bok_Rank");
                Onbok_RankChanged();
            }
        }
        private global::System.String _bok_Rank;
        partial void Onbok_RankChanging(global::System.String value);
        partial void Onbok_RankChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String bok_ISBN
        {
            get
            {
                return _bok_ISBN;
            }
            set
            {
                Onbok_ISBNChanging(value);
                ReportPropertyChanging("bok_ISBN");
                _bok_ISBN = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("bok_ISBN");
                Onbok_ISBNChanged();
            }
        }
        private global::System.String _bok_ISBN;
        partial void Onbok_ISBNChanging(global::System.String value);
        partial void Onbok_ISBNChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String bok_ImageURl
        {
            get
            {
                return _bok_ImageURl;
            }
            set
            {
                Onbok_ImageURlChanging(value);
                ReportPropertyChanging("bok_ImageURl");
                _bok_ImageURl = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("bok_ImageURl");
                Onbok_ImageURlChanged();
            }
        }
        private global::System.String _bok_ImageURl;
        partial void Onbok_ImageURlChanging(global::System.String value);
        partial void Onbok_ImageURlChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> pbl_ID
        {
            get
            {
                return _pbl_ID;
            }
            set
            {
                Onpbl_IDChanging(value);
                ReportPropertyChanging("pbl_ID");
                _pbl_ID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("pbl_ID");
                Onpbl_IDChanged();
            }
        }
        private Nullable<global::System.Int32> _pbl_ID;
        partial void Onpbl_IDChanging(Nullable<global::System.Int32> value);
        partial void Onpbl_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> bok_Modified
        {
            get
            {
                return _bok_Modified;
            }
            set
            {
                Onbok_ModifiedChanging(value);
                ReportPropertyChanging("bok_Modified");
                _bok_Modified = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("bok_Modified");
                Onbok_ModifiedChanged();
            }
        }
        private Nullable<global::System.Boolean> _bok_Modified;
        partial void Onbok_ModifiedChanging(Nullable<global::System.Boolean> value);
        partial void Onbok_ModifiedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ctg_ID
        {
            get
            {
                return _ctg_ID;
            }
            set
            {
                Onctg_IDChanging(value);
                ReportPropertyChanging("ctg_ID");
                _ctg_ID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ctg_ID");
                Onctg_IDChanged();
            }
        }
        private Nullable<global::System.Int32> _ctg_ID;
        partial void Onctg_IDChanging(Nullable<global::System.Int32> value);
        partial void Onctg_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> lng_ID
        {
            get
            {
                return _lng_ID;
            }
            set
            {
                Onlng_IDChanging(value);
                ReportPropertyChanging("lng_ID");
                _lng_ID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("lng_ID");
                Onlng_IDChanged();
            }
        }
        private Nullable<global::System.Int32> _lng_ID;
        partial void Onlng_IDChanging(Nullable<global::System.Int32> value);
        partial void Onlng_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String bok_Location
        {
            get
            {
                return _bok_Location;
            }
            set
            {
                Onbok_LocationChanging(value);
                ReportPropertyChanging("bok_Location");
                _bok_Location = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("bok_Location");
                Onbok_LocationChanged();
            }
        }
        private global::System.String _bok_Location;
        partial void Onbok_LocationChanging(global::System.String value);
        partial void Onbok_LocationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> bok_Volume
        {
            get
            {
                return _bok_Volume;
            }
            set
            {
                Onbok_VolumeChanging(value);
                ReportPropertyChanging("bok_Volume");
                _bok_Volume = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("bok_Volume");
                Onbok_VolumeChanged();
            }
        }
        private Nullable<global::System.Int32> _bok_Volume;
        partial void Onbok_VolumeChanging(Nullable<global::System.Int32> value);
        partial void Onbok_VolumeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> seri_ID
        {
            get
            {
                return _seri_ID;
            }
            set
            {
                Onseri_IDChanging(value);
                ReportPropertyChanging("seri_ID");
                _seri_ID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("seri_ID");
                Onseri_IDChanged();
            }
        }
        private Nullable<global::System.Int32> _seri_ID;
        partial void Onseri_IDChanging(Nullable<global::System.Int32> value);
        partial void Onseri_IDChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LibraryModel", "fk_Book_publisher", "Publisher")]
        public Publisher Publisher
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Publisher>("LibraryModel.fk_Book_publisher", "Publisher").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Publisher>("LibraryModel.fk_Book_publisher", "Publisher").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Publisher> PublisherReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Publisher>("LibraryModel.fk_Book_publisher", "Publisher");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Publisher>("LibraryModel.fk_Book_publisher", "Publisher", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LibraryModel", "Author_Book", "Author")]
        public EntityCollection<Author> Authors
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Author>("LibraryModel.Author_Book", "Author");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Author>("LibraryModel.Author_Book", "Author", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LibraryModel", "fk_Category_Book_ctgID", "Category")]
        public Category Category
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Category>("LibraryModel.fk_Category_Book_ctgID", "Category").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Category>("LibraryModel.fk_Category_Book_ctgID", "Category").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Category> CategoryReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Category>("LibraryModel.fk_Category_Book_ctgID", "Category");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Category>("LibraryModel.fk_Category_Book_ctgID", "Category", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LibraryModel", "Tag_Book", "Tag")]
        public EntityCollection<Tag> Tags
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Tag>("LibraryModel.Tag_Book", "Tag");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Tag>("LibraryModel.Tag_Book", "Tag", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LibraryModel", "fk_Book_Language_lngID", "Language")]
        public Language Language
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Language>("LibraryModel.fk_Book_Language_lngID", "Language").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Language>("LibraryModel.fk_Book_Language_lngID", "Language").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Language> LanguageReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Language>("LibraryModel.fk_Book_Language_lngID", "Language");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Language>("LibraryModel.fk_Book_Language_lngID", "Language", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LibraryModel", "fk_Book_Seri_seriID", "Seri")]
        public Seri Seri
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Seri>("LibraryModel.fk_Book_Seri_seriID", "Seri").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Seri>("LibraryModel.fk_Book_Seri_seriID", "Seri").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Seri> SeriReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Seri>("LibraryModel.fk_Book_Seri_seriID", "Seri");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Seri>("LibraryModel.fk_Book_Seri_seriID", "Seri", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LibraryModel", Name="Category")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Category : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Category object.
        /// </summary>
        /// <param name="ctg_ID">Initial value of the ctg_ID property.</param>
        public static Category CreateCategory(global::System.Int32 ctg_ID)
        {
            Category category = new Category();
            category.ctg_ID = ctg_ID;
            return category;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ctg_ID
        {
            get
            {
                return _ctg_ID;
            }
            set
            {
                if (_ctg_ID != value)
                {
                    Onctg_IDChanging(value);
                    ReportPropertyChanging("ctg_ID");
                    _ctg_ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ctg_ID");
                    Onctg_IDChanged();
                }
            }
        }
        private global::System.Int32 _ctg_ID;
        partial void Onctg_IDChanging(global::System.Int32 value);
        partial void Onctg_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ctg_Name
        {
            get
            {
                return _ctg_Name;
            }
            set
            {
                Onctg_NameChanging(value);
                ReportPropertyChanging("ctg_Name");
                _ctg_Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ctg_Name");
                Onctg_NameChanged();
            }
        }
        private global::System.String _ctg_Name;
        partial void Onctg_NameChanging(global::System.String value);
        partial void Onctg_NameChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LibraryModel", "fk_Category_Book_ctgID", "Book")]
        public EntityCollection<Book> Books
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Book>("LibraryModel.fk_Category_Book_ctgID", "Book");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Book>("LibraryModel.fk_Category_Book_ctgID", "Book", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LibraryModel", Name="Language")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Language : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Language object.
        /// </summary>
        /// <param name="lng_ID">Initial value of the lng_ID property.</param>
        public static Language CreateLanguage(global::System.Int32 lng_ID)
        {
            Language language = new Language();
            language.lng_ID = lng_ID;
            return language;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 lng_ID
        {
            get
            {
                return _lng_ID;
            }
            set
            {
                if (_lng_ID != value)
                {
                    Onlng_IDChanging(value);
                    ReportPropertyChanging("lng_ID");
                    _lng_ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("lng_ID");
                    Onlng_IDChanged();
                }
            }
        }
        private global::System.Int32 _lng_ID;
        partial void Onlng_IDChanging(global::System.Int32 value);
        partial void Onlng_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String lng_Name
        {
            get
            {
                return _lng_Name;
            }
            set
            {
                Onlng_NameChanging(value);
                ReportPropertyChanging("lng_Name");
                _lng_Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("lng_Name");
                Onlng_NameChanged();
            }
        }
        private global::System.String _lng_Name;
        partial void Onlng_NameChanging(global::System.String value);
        partial void Onlng_NameChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LibraryModel", "fk_Book_Language_lngID", "Book")]
        public EntityCollection<Book> Books
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Book>("LibraryModel.fk_Book_Language_lngID", "Book");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Book>("LibraryModel.fk_Book_Language_lngID", "Book", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LibraryModel", Name="Publisher")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Publisher : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Publisher object.
        /// </summary>
        /// <param name="pbl_ID">Initial value of the pbl_ID property.</param>
        public static Publisher CreatePublisher(global::System.Int32 pbl_ID)
        {
            Publisher publisher = new Publisher();
            publisher.pbl_ID = pbl_ID;
            return publisher;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 pbl_ID
        {
            get
            {
                return _pbl_ID;
            }
            set
            {
                if (_pbl_ID != value)
                {
                    Onpbl_IDChanging(value);
                    ReportPropertyChanging("pbl_ID");
                    _pbl_ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("pbl_ID");
                    Onpbl_IDChanged();
                }
            }
        }
        private global::System.Int32 _pbl_ID;
        partial void Onpbl_IDChanging(global::System.Int32 value);
        partial void Onpbl_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String pbl_Name
        {
            get
            {
                return _pbl_Name;
            }
            set
            {
                Onpbl_NameChanging(value);
                ReportPropertyChanging("pbl_Name");
                _pbl_Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("pbl_Name");
                Onpbl_NameChanged();
            }
        }
        private global::System.String _pbl_Name;
        partial void Onpbl_NameChanging(global::System.String value);
        partial void Onpbl_NameChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LibraryModel", "fk_Book_publisher", "Book")]
        public EntityCollection<Book> Books
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Book>("LibraryModel.fk_Book_publisher", "Book");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Book>("LibraryModel.fk_Book_publisher", "Book", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LibraryModel", Name="Seri")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Seri : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Seri object.
        /// </summary>
        /// <param name="seri_ID">Initial value of the seri_ID property.</param>
        public static Seri CreateSeri(global::System.Int32 seri_ID)
        {
            Seri seri = new Seri();
            seri.seri_ID = seri_ID;
            return seri;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 seri_ID
        {
            get
            {
                return _seri_ID;
            }
            set
            {
                if (_seri_ID != value)
                {
                    Onseri_IDChanging(value);
                    ReportPropertyChanging("seri_ID");
                    _seri_ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("seri_ID");
                    Onseri_IDChanged();
                }
            }
        }
        private global::System.Int32 _seri_ID;
        partial void Onseri_IDChanging(global::System.Int32 value);
        partial void Onseri_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String seri_Name
        {
            get
            {
                return _seri_Name;
            }
            set
            {
                Onseri_NameChanging(value);
                ReportPropertyChanging("seri_Name");
                _seri_Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("seri_Name");
                Onseri_NameChanged();
            }
        }
        private global::System.String _seri_Name;
        partial void Onseri_NameChanging(global::System.String value);
        partial void Onseri_NameChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LibraryModel", "fk_Book_Seri_seriID", "Book")]
        public EntityCollection<Book> Books
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Book>("LibraryModel.fk_Book_Seri_seriID", "Book");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Book>("LibraryModel.fk_Book_Seri_seriID", "Book", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LibraryModel", Name="Tag")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Tag : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Tag object.
        /// </summary>
        /// <param name="tag_ID">Initial value of the tag_ID property.</param>
        public static Tag CreateTag(global::System.Int32 tag_ID)
        {
            Tag tag = new Tag();
            tag.tag_ID = tag_ID;
            return tag;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 tag_ID
        {
            get
            {
                return _tag_ID;
            }
            set
            {
                if (_tag_ID != value)
                {
                    Ontag_IDChanging(value);
                    ReportPropertyChanging("tag_ID");
                    _tag_ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("tag_ID");
                    Ontag_IDChanged();
                }
            }
        }
        private global::System.Int32 _tag_ID;
        partial void Ontag_IDChanging(global::System.Int32 value);
        partial void Ontag_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String tag_Name
        {
            get
            {
                return _tag_Name;
            }
            set
            {
                Ontag_NameChanging(value);
                ReportPropertyChanging("tag_Name");
                _tag_Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("tag_Name");
                Ontag_NameChanged();
            }
        }
        private global::System.String _tag_Name;
        partial void Ontag_NameChanging(global::System.String value);
        partial void Ontag_NameChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LibraryModel", "Tag_Book", "Book")]
        public EntityCollection<Book> Books
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Book>("LibraryModel.Tag_Book", "Book");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Book>("LibraryModel.Tag_Book", "Book", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
